services:
  - type: web
    plan: free
    name: python-weather
    runtime: python
    repo: https://github.com/mosslman/python-weather
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker
